### ISSUE TITLE
Confluent Sttp crashes on ` org.apache.avro.SchemaParseException: Can't redefine`

### ISSUE THREAD

**Issue by Fristi** [vectos/formulation#39]
**Version**: (e.g. `0.4.0`)
**Module**: (e.g. `formulation-schema-registry-confluent-sttp`)

### Expected behavior

Process messages correctly

### Actual behavior

Throws a exception when messages redefine the same entity

```

 org.apache.avro.SchemaParseException: Can't redefine: <<entity-name>>
 	at org.apache.avro.Schema$Names.put(Schema.java:1128)
 	at org.apache.avro.Schema$Names.add(Schema.java:1123)
 	at org.apache.avro.Schema.parse(Schema.java:1253)
 	at org.apache.avro.Schema.parse(Schema.java:1269)
 	at org.apache.avro.Schema$Parser.parse(Schema.java:1032)
 	at org.apache.avro.Schema$Parser.parse(Schema.java:1020)
 	at formulation.schemaregistry.confluent.sttp.ConfluentSttpSchemaRegistryClient$$anonfun$formulation$schemaregistry$confluent$sttp$ConfluentSttpSchemaRegistryClient$$parseResponse$1$2$$anonfun$apply$7.apply(yClient.scala:23)
 	at formulation.schemaregistry.confluent.sttp.ConfluentSttpSchemaRegistryClient$$anonfun$formulation$schemaregistry$confluent$sttp$ConfluentSttpSchemaRegistryClient$$parseResponse$1$2$$anonfun$apply$7.apply(yClient.scala:23)
 	at scala.util.Try$.apply(Try.scala:192)
 	at formulation.schemaregistry.confluent.sttp.ConfluentSttpSchemaRegistryClient$$anonfun$formulation$schemaregistry$confluent$sttp$ConfluentSttpSchemaRegistryClient$$parseResponse$1$2.apply(yClient.scala:23)
 	at formulation.schemaregistry.confluent.sttp.ConfluentSttpSchemaRegistryClient$$anonfun$formulation$schemaregistry$confluent$sttp$ConfluentSttpSchemaRegistryClient$$parseResponse$1$2.apply(yClient.scala:22)
 	at scala.util.Success.flatMap(Try.scala:231)
 	at cats.instances.TryInstances$$anon$1.flatMap(try.scala:35)
 	at cats.instances.TryInstances$$anon$1.flatMap(try.scala:14)
 	at cats.FlatMap$Ops$class.flatMap(FlatMap.scala:21)
 	at cats.FlatMap$ToFlatMapOps$$anon$2.flatMap(FlatMap.scala:21)
```

### Possible solution

Don't re-use the `Schema.Parser`

**Comment by Fristi** [comment]
Solved in (https://github.com/vectos/formulation/commit/f708da6852abf3d1b26a64ed221f311574d46b60)
